pipelines:
  default:
    - step:
        name: Build and Test
        script:
          - echo "Running unit tests..."
          - python -m unittest discover tests/
    - step:
        name: Deploy Infrastructure
        script:
          - echo "Initializing Terraform..."
          - terraform init
          - echo "Applying Terraform..."
          - terraform apply -auto-approve
